[package]
name = "dungeons"
version = "0.1.0"
edition = "2021"

# [target.x86_64-pc-windows-msvc]
# linker = "rust-lld.exe"
# rustflags = ["-Zshare-generics=off"]

[dependencies]
bevy = { version = "0.9.0", features = ["dynamic"] }
bevy_ecs_tilemap = "0.9.0"
rand = "0.8.5"